{
 "title": "Business Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number Of Present Videos",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_present_videos", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number Of Playlists",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_present_playlists", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentage of Videos Per Playlists",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_videos_per_playlist{namespace=\"microservices\"}",
     "legendFormat": "{{playlist}}"
    }
   ]
  },
  {
   "title": "Top 3 Playlists",
   "type": "bargauge",
   "description": "Top 3 Playlists in terms of the number of videos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, number_of_videos_per_playlist)",
     "legendFormat": "{{ playlist }}"
    }
   ]
  }
 ]
}