{
 "title": "Redis Database Metrics",
 "description": "A Redis Server Performance Monitoring Redis Server with Prometheus and telegraf agent using Redis agent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(redis_uptime_in_seconds,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Genral Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Clusters",
   "type": "stat",
   "description": "Total Clusters Enabled",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_cluster_enabled{pod=\"$pod\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "cluster_enabled" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Connection Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connections_received_total{pod=\"$pod\"}",
     "legendFormat": "$Server"
    }
   ]
  },
  {
   "title": "Total Clients Connected",
   "type": "stat",
   "description": "Total Clients Connected",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(redis_connected_clients{pod=\"redis-master-0\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "clients" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis User CPU",
   "type": "timeseries",
   "description": "User CPU consumed by the Redis server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Uuser CPU",
     "expr": "sum by (pod)(irate(redis_cpu_user_seconds_total{pod=~\"$pod\"}[10m])) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "Redis User CPU",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_cpu_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis Up Time",
   "type": "timeseries",
   "description": "Redis Up Time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{pod=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "redis",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Redis Memory Utilization",
   "type": "timeseries",
   "description": "Total number of bytes allocated by Redis using its allocator",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Total Used Memory",
     "expr": "redis_memory_used_bytes{pod=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "mem_used",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "used_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "redis_used_memory_lua{instance=~\"$Server\"}",
     "legendFormat": "mem_lua"
    },
    {
     "expr": "redis_used_memory_peak{instance=\"$Server\"}",
     "legendFormat": "mem_peak"
    },
    {
     "expr": "redis_used_memory_rss{instance=\"$Server\"}",
     "legendFormat": "mem_rss"
    }
   ]
  },
  {
   "title": "RedisperCacheStats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hit / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_keyspace_misses_total{pod=\"$pod\"}",
     "legendFormat": "redis_hitrate"
    },
    {
     "expr": "redis_keyspace_misses{instance=\"$Server\"}",
     "legendFormat": "redis_missrate"
    }
   ]
  },
  {
   "title": "Total Tracking Items",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_tracking_total_items{pod=\"$pod\"}",
     "legendFormat": "total_tracking_items"
    }
   ]
  },
  {
   "title": "Evicted / Expired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_evicted_keys_total{pod=\"$pod\"}",
     "legendFormat": "evicted_keys"
    },
    {
     "expr": "redis_expired_keys{instance=\"$Server\"}",
     "legendFormat": "expirted_keys"
    }
   ]
  },
  {
   "title": "Total Keyspaces",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_tracking_total_keys{pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "timeseries",
   "description": "Total number of commands processed by the server",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Total Commands Processed",
     "expr": "sum by (pod)(irate(redis_commands_total{pod=~\"$pod\"}[5m]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "processed_commands",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_commands_processed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocked / Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_blocked_clients{pod=\"$pod\"}",
     "legendFormat": "blocked_clients"
    },
    {
     "expr": "redis_tracking_clients{instance=\"$Server\"}",
     "legendFormat": "connected_clients"
    }
   ]
  },
  {
   "title": "RedisperformanceStats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received / Rejected Connections",
   "type": "timeseries",
   "description": "Total number of connections accepted by the server",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Total Connections Received",
     "expr": "sum by (pod)(irate(redis_connections_received_total{pod=~\"$pod\"}[10m])) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "legendFormat": "received",
     "measurement": "redis",
     "select": [
      [
       { "params": [ "total_connections_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/^$Server$/" }
     ]
    },
    {
     "expr": "sum by (instance)(irate(redis_rejected_connections{instance=~\"$Server\"}[10m])) * 100",
     "legendFormat": "rejected"
    }
   ]
  },
  {
   "title": "Network Input / Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_net_input_bytes_total{pod=\"$pod\"}",
     "legendFormat": "input_bytes"
    },
    {
     "expr": "redis_total_net_output_bytes{instance=\"$Server\"}",
     "legendFormat": "output_bytes"
    }
   ]
  }
 ]
}