{
 "title": "Videos-API-Metrics",
 "description": "Videos API Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"microservices\",pod=~\"videos.*\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "20x HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\", container=\"videos-api-container\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50x HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=~\"500|503\", container=\"videos-api-container\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of requests in flight",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_in_flight{container=\"videos-api-container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Http Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{container=\"videos-api-container\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "General Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"} - go_memstats_other_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}",
       "legendFormat": "bytes of memory are used for other runtime allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{namespace=\"microservices\", pod=~\"$pod\"} - go_memstats_frees_total{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{namespace=\"microservices\", pod=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Rate of a Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{namespace=\"microservices\", pod=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"microservices\", pod=~\"$pod\"}[1m])"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"microservices\", pod=~\"$pod\"}"
      }
     ]
    }
   ]
  }
 ]
}